const MAX_ITERATIONS = 9999;

const ARENA_WIDTH = 400;
const ARENA_HEIGHT = 400;
const MAX_DISTANCE = Math.sqrt(ARENA_WIDTH ** 2 + ARENA_HEIGHT ** 2);

const TANK_SIZE = 6;
const MAX_TANK_ENERGY = 1000;
const MAX_ACTUAL_SPEED = TANK_SIZE / 2.5;
const MAX_BODY_TURN_DEGREES = 10;
const MAX_GUN_TURN_DEGREES = 15;
const MAX_RADAR_TURN_DEGREES = 45;
const MAX_RADAR_ARC_DEGREES = 90;

const MISSILE_SPEED = 10;
const MIN_MISSILE_SIZE = 1;
const MAX_MISSILE_SIZE = TANK_SIZE / 10;
const MAX_MISSILE_ENERGY = 50;
const MISSILE_ENERGY_MULTIPLIER = 4;

const PI = Math.PI;
const DEGREES = 180 / Math.PI;
const RADIANS = Math.PI / 180;

const SURVIVAL_BONUS_POINTS = 1000;
const ACCURACY_BONUS_POINTS = 1000;
const DAMAGE_DEALT_POINTS = 1;
